import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import {
  Calendar,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  X,
  Sparkles,
} from 'lucide-react';
import { LIFE_AT_REQUIN_GALLERY, GalleryImage, GalleryPhotoItem } from '../data/requinData';
import { lifeAtRequinService } from '../services/lifeAtRequinService';
import { getMediaUrl } from '../utils/mediaUrl';

/**
 * Detects if a title or string is an auto-generated file hash, camera filename, timestamp, or raw upload artifact.
 */
export const isAutoGeneratedTitle = (title?: string): boolean => {
  if (!title || !title.trim()) return true;
  const t = title.trim();

  // Pure numbers, timestamps, or simple numeric sequences (e.g. "1144 3", "1409 7", "20240510", "17123456789")
  if (/^[0-9\s_#-]+$/.test(t)) return true;

  // File extension remnants
  if (/\.(jpg|jpeg|png|webp|avif|gif|svg|bmp)$/i.test(t)) return true;

  // Camera, phone, app or platform prefixes or tokens (e.g. "IMG 1409", "DSC_001", "WhatsApp Image")
  if (/\b(img|dsc|pxl|photo|pic|image|dcim|whatsapp|screenshot|capture|media|asset|vid|wp|file)\b/i.test(t)) {
    return true;
  }

  // Known hash prefixes or raw upload IDs (e.g. Zyyk..., Zyyai..., Zyyab..., ZyyaN..., etc.)
  if (/^zyy/i.test(t) || /\bzyy[a-z0-9]+/i.test(t)) return true;

  // Random hash tokens (6+ characters with mixed alphanumeric or mixed casing)
  const words = t.split(/\s+/);
  for (const w of words) {
    if (w.length >= 6 && /[0-9]/.test(w) && /[a-zA-Z]/.test(w)) {
      return true;
    }
    if (w.length >= 8 && /[a-z]/.test(w) && /[A-Z]/.test(w)) {
      return true;
    }
  }

  return false;
};

/**
 * Returns the custom title only if the user explicitly entered a valid title, otherwise null.
 */
export const getCustomPhotoTitle = (photoTitle?: string, fallbackAlbumTitle?: string): string | null => {
  if (!photoTitle || isAutoGeneratedTitle(photoTitle) || (fallbackAlbumTitle && photoTitle.trim() === fallbackAlbumTitle.trim())) {
    return null;
  }
  return photoTitle.trim();
};

/**
 * Returns the custom caption/subtitle only if entered and not auto-generated, otherwise null.
 */
export const getCustomPhotoCaption = (caption?: string): string | null => {
  if (!caption || isAutoGeneratedTitle(caption) || !caption.trim()) {
    return null;
  }
  return caption.trim();
};

export const LifeAtRequinSection: React.FC = () => {
  const [galleries, setGalleries] = useState<GalleryImage[]>(LIFE_AT_REQUIN_GALLERY);
  const [activeIndex, setActiveIndex] = useState<number>(0);
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [modalActiveIndex, setModalActiveIndex] = useState<number>(0);
  const [modalSelectedYear, setModalSelectedYear] = useState<string>('All');
  const [modalPhotoIndex, setModalPhotoIndex] = useState<number>(0);

  // Fetch dynamic CMS data
  useEffect(() => {
    let isMounted = true;
    lifeAtRequinService.getPublishedGalleries()
      .then((res) => {
        if (isMounted && res.success && res.data && res.data.length > 0) {
          setGalleries(res.data);
        }
      })
      .catch(() => {
        // Silently fallback to default data
      });
    return () => {
      isMounted = false;
    };
  }, []);

  // Touch swipe support
  const touchStartXRef = useRef<number | null>(null);
  const touchEndXRef = useRef<number | null>(null);

  const filteredList: GalleryImage[] = galleries.length > 0 ? galleries : LIFE_AT_REQUIN_GALLERY;

  // Safe carousel navigation
  const handlePrev = useCallback(() => {
    if (filteredList.length <= 1) return;
    setActiveIndex((prev) => (prev === 0 ? filteredList.length - 1 : prev - 1));
  }, [filteredList.length]);

  const handleNext = useCallback(() => {
    if (filteredList.length <= 1) return;
    setActiveIndex((prev) => (prev === filteredList.length - 1 ? 0 : prev + 1));
  }, [filteredList.length]);

  // Continuous Auto-Advancing Moving State (Auto-slides every 2 seconds)
  useEffect(() => {
    if (isModalOpen || filteredList.length <= 1) return;

    const interval = setInterval(() => {
      setActiveIndex((prev) => (prev + 1) % filteredList.length);
    }, 2000);

    return () => clearInterval(interval);
  }, [isModalOpen, filteredList.length, activeIndex]);

  const activeModalItem = filteredList[modalActiveIndex] || filteredList[0];

  // Derive photos for the active modal event - sorted in descending order of year (e.g., 2026 -> 2025 -> 2024)
  const allEventPhotos: GalleryPhotoItem[] = useMemo(() => {
    const raw =
      activeModalItem?.photos && activeModalItem.photos.length > 0
        ? [...activeModalItem.photos]
        : [
            {
              id: activeModalItem?.id || 'photo-default',
              image: activeModalItem?.image || '',
              year: activeModalItem?.date || '2026',
              title: activeModalItem?.title || '',
              caption: activeModalItem?.caption || '',
            },
          ];

    return raw.sort((a, b) => {
      const yearA = parseInt(String(a.year || '').replace(/\D/g, ''), 10) || 0;
      const yearB = parseInt(String(b.year || '').replace(/\D/g, ''), 10) || 0;
      return yearB - yearA; // Descending: 2026 -> 2025 -> 2024
    });
  }, [activeModalItem]);

  const availableYears: string[] = useMemo(() => {
    const rawYears =
      activeModalItem?.years && activeModalItem.years.length > 0
        ? [...activeModalItem.years]
        : Array.from(new Set(allEventPhotos.map((p) => p.year).filter(Boolean)));

    return Array.from(new Set(rawYears)).sort((a, b) => {
      const yearA = parseInt(String(a).replace(/\D/g, ''), 10) || 0;
      const yearB = parseInt(String(b).replace(/\D/g, ''), 10) || 0;
      return yearB - yearA; // Descending: 2026 -> 2025 -> 2024
    });
  }, [activeModalItem, allEventPhotos]);

  const displayedPhotos: GalleryPhotoItem[] = useMemo(() => {
    if (modalSelectedYear === 'All') {
      return allEventPhotos;
    }
    return allEventPhotos.filter((p) => p.year === modalSelectedYear);
  }, [allEventPhotos, modalSelectedYear]);

  const safePhotos: GalleryPhotoItem[] =
    displayedPhotos.length > 0 ? displayedPhotos : allEventPhotos;

  const currentActivePhoto: GalleryPhotoItem =
    safePhotos[modalPhotoIndex] || safePhotos[0] || allEventPhotos[0];

  // Modal navigation within photos
  const handleModalPrev = useCallback(() => {
    if (safePhotos.length <= 1) return;
    setModalPhotoIndex((prev) => (prev === 0 ? safePhotos.length - 1 : prev - 1));
  }, [safePhotos.length]);

  const handleModalNext = useCallback(() => {
    if (safePhotos.length <= 1) return;
    setModalPhotoIndex((prev) => (prev === safePhotos.length - 1 ? 0 : prev + 1));
  }, [safePhotos.length]);

  const handleYearChange = (year: string) => {
    setModalSelectedYear(year);
    setModalPhotoIndex(0);
  };

  const handleOpenModal = (index: number) => {
    setModalActiveIndex(index);
    setModalSelectedYear('All');
    setModalPhotoIndex(0);
    setIsModalOpen(true);
  };

  // Lock background page scroll when modal is open
  useEffect(() => {
    if (isModalOpen) {
      const originalOverflow = document.body.style.overflow;
      const originalPaddingRight = document.body.style.paddingRight;
      const scrollBarWidth = window.innerWidth - document.documentElement.clientWidth;

      document.body.style.overflow = 'hidden';
      if (scrollBarWidth > 0) {
        document.body.style.paddingRight = `${scrollBarWidth}px`;
      }

      return () => {
        document.body.style.overflow = originalOverflow;
        document.body.style.paddingRight = originalPaddingRight;
      };
    }
  }, [isModalOpen]);

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (isModalOpen) {
        if (e.key === 'Escape') setIsModalOpen(false);
        if (e.key === 'ArrowLeft') handleModalPrev();
        if (e.key === 'ArrowRight') handleModalNext();
      } else {
        if (e.key === 'ArrowLeft') handlePrev();
        if (e.key === 'ArrowRight') handleNext();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isModalOpen, handleModalPrev, handleModalNext, handlePrev, handleNext]);

  // Touch handlers
  const handleTouchStart = (e: React.TouchEvent) => {
    touchStartXRef.current = e.targetTouches[0].clientX;
  };

  const handleTouchMove = (e: React.TouchEvent) => {
    touchEndXRef.current = e.targetTouches[0].clientX;
  };

  const handleTouchEnd = () => {
    if (touchStartXRef.current !== null && touchEndXRef.current !== null) {
      const distance = touchStartXRef.current - touchEndXRef.current;
      if (distance > 45) {
        handleNext();
      } else if (distance < -45) {
        handlePrev();
      }
    }
    touchStartXRef.current = null;
    touchEndXRef.current = null;
  };

  // Card click behavior
  const handleCardClick = (index: number) => {
    if (index === activeIndex) {
      handleOpenModal(index);
    } else {
      setActiveIndex(index);
    }
  };

  return (
    <section
      id="life-at-requin"
      className="pt-8 sm:pt-12 md:pt-14 pb-16 sm:pb-20 md:pb-24 bg-[#F5FAFD] text-[#071827] relative overflow-hidden selection:bg-[#08B9E8]/20 selection:text-[#08B9E8]"
      onTouchStart={handleTouchStart}
      onTouchMove={handleTouchMove}
      onTouchEnd={handleTouchEnd}
    >
      {/* Background Ambience Animations */}
      <style>{`
        @keyframes ambientFloatLife {
          0%, 100% {
            transform: translate(0, 0) scale(1);
          }
          50% {
            transform: translate(-8px, -10px) scale(1.03);
          }
        }
        @keyframes networkPulseLife {
          0%, 100% {
            opacity: 0.7;
          }
          50% {
            opacity: 1;
          }
        }
        .animate-ambient-life {
          animation: ambientFloatLife 16s ease-in-out infinite;
        }
        .animate-network-life {
          animation: networkPulseLife 12s ease-in-out infinite;
        }
      `}</style>

      {/* ========================================================
          BACKGROUND LAYER 1: Ambient Glows
      ======================================================== */}
      <div className="absolute inset-0 pointer-events-none z-0 overflow-hidden">
        <div className="absolute -top-24 -left-20 w-[750px] h-[550px] bg-[radial-gradient(circle_at_30%_30%,rgba(8,185,232,0.18),transparent_65%)] blur-[100px] animate-ambient-life" />
        <div
          className="absolute -top-20 -right-20 w-[700px] h-[520px] bg-[radial-gradient(circle_at_70%_30%,rgba(0,194,255,0.16),transparent_65%)] blur-[100px] animate-ambient-life"
          style={{ animationDelay: '-5s' }}
        />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[850px] h-[550px] bg-[radial-gradient(circle,rgba(8,185,232,0.12),transparent_70%)] blur-[120px] pointer-events-none" />
        <div
          className="absolute -bottom-24 -right-16 w-[720px] h-[540px] bg-[radial-gradient(circle_at_70%_70%,rgba(2,132,199,0.14),transparent_65%)] blur-[100px] animate-ambient-life"
          style={{ animationDelay: '-3s' }}
        />
      </div>

      {/* ========================================================
          BACKGROUND LAYER 2: Digital Network Constellation Web
      ======================================================== */}
      <svg
        className="absolute inset-0 w-full h-full pointer-events-none z-0 animate-network-life"
        xmlns="http://www.w3.org/2000/svg"
        preserveAspectRatio="none"
      >
        <defs>
          <linearGradient id="netGradLife" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#08B9E8" stopOpacity="0.14" />
            <stop offset="50%" stopColor="#00c2ff" stopOpacity="0.08" />
            <stop offset="100%" stopColor="#0284c7" stopOpacity="0.12" />
          </linearGradient>
        </defs>

        <g stroke="url(#netGradLife)" strokeWidth="1" fill="none">
          <line x1="5%" y1="12%" x2="12%" y2="22%" />
          <line x1="12%" y1="22%" x2="8%" y2="35%" />
          <line x1="12%" y1="22%" x2="19%" y2="28%" />
          <line x1="95%" y1="14%" x2="88%" y2="24%" />
          <line x1="88%" y1="24%" x2="92%" y2="38%" />
        </g>
        <g fill="#08B9E8">
          <circle cx="5%" cy="12%" r="3" fillOpacity="0.4" />
          <circle cx="12%" cy="22%" r="2" fillOpacity="0.85" />
          <circle cx="8%" cy="35%" r="2.5" fillOpacity="0.4" />
          <circle cx="19%" cy="28%" r="3" fillOpacity="0.4" />
          <circle cx="95%" cy="14%" r="3" fillOpacity="0.4" />
          <circle cx="88%" cy="24%" r="1.5" fillOpacity="0.85" />
          <circle cx="92%" cy="38%" r="2.5" fillOpacity="0.4" />
        </g>
      </svg>

      {/* ========================================================
          MAIN CONTENT LAYER
      ======================================================== */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Section Header */}
        <div className="max-w-3xl mb-6 sm:mb-8 md:mb-10 text-left">
          <div className="text-sm sm:text-base font-bold tracking-[0.2em] text-[#08B9E8] uppercase mb-2 flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-[#08B9E8]" />
            TEAM & CULTURE
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-[#071827] tracking-[-0.03em] leading-tight">
            Life at <span className="text-[#08B9E8]">Requin</span>
          </h2>
          <p className="mt-3 text-base sm:text-lg text-slate-600 font-normal leading-[1.6]">
            Where people, ideas, and technology come together. Glimpse into our company celebrations, team hackathons, and collaborative culture.
          </p>
        </div>

        {/* ========================================================
            CENTER-FOCUSED 3D COVERFLOW MOVING CAROUSEL
        ======================================================== */}
        <div className="relative w-full max-w-6xl mx-auto h-[380px] sm:h-[440px] md:h-[480px] lg:h-[500px] flex items-center justify-center my-2 sm:my-3">
          {/* Left Arrow Control */}
          <button
            onClick={handlePrev}
            aria-label="Previous event"
            className="absolute left-1 sm:left-4 md:left-6 top-1/2 -translate-y-1/2 z-40 w-11 h-11 sm:w-13 sm:h-13 rounded-full bg-white/95 backdrop-blur-md border border-[#D8E5EC] text-[#071827] shadow-lg hover:border-[#08B9E8] hover:text-[#08B9E8] hover:shadow-[0_0_25px_rgba(8,185,232,0.35)] hover:scale-105 active:scale-95 transition-all duration-200 flex items-center justify-center focus:outline-none focus:ring-2 focus:ring-[#08B9E8] cursor-pointer"
          >
            <ChevronLeft className="w-6 h-6 sm:w-7 sm:h-7" />
          </button>

          {/* Right Arrow Control */}
          <button
            onClick={handleNext}
            aria-label="Next event"
            className="absolute right-1 sm:right-4 md:right-6 top-1/2 -translate-y-1/2 z-40 w-11 h-11 sm:w-13 sm:h-13 rounded-full bg-white/95 backdrop-blur-md border border-[#D8E5EC] text-[#071827] shadow-lg hover:border-[#08B9E8] hover:text-[#08B9E8] hover:shadow-[0_0_25px_rgba(8,185,232,0.35)] hover:scale-105 active:scale-95 transition-all duration-200 flex items-center justify-center focus:outline-none focus:ring-2 focus:ring-[#08B9E8] cursor-pointer"
          >
            <ChevronRight className="w-6 h-6 sm:w-7 sm:h-7" />
          </button>

          {/* 3D Coverflow Stage Cards */}
          <div className="relative w-full h-full flex items-center justify-center overflow-visible">
            {filteredList.map((item, idx) => {
              const total = filteredList.length;
              if (total === 0) return null;

              // Calculate shortest circular difference
              let diff = idx - activeIndex;
              if (total > 2) {
                diff = ((idx - activeIndex) % total + total) % total;
                if (diff > total / 2) diff -= total;
              }

              const isCenter = diff === 0;

              // Compute transforms and styling based on position
              let translateX = '0%';
              let scale = 1;
              let opacity = 1;
              let blur = 0;
              let zIndex = 30;
              let pointerEvents: 'auto' | 'none' = 'auto';

              if (isCenter) {
                translateX = '0%';
                scale = 1;
                opacity = 1;
                blur = 0;
                zIndex = 30;
              } else if (diff === -1 || (total <= 2 && !isCenter && idx < activeIndex)) {
                translateX = '-65%';
                scale = 0.82;
                opacity = 0.65;
                blur = 2.5;
                zIndex = 10;
              } else if (diff === 1 || (total <= 2 && !isCenter && idx > activeIndex)) {
                translateX = '65%';
                scale = 0.82;
                opacity = 0.65;
                blur = 2.5;
                zIndex = 10;
              } else {
                // Offstage cards
                translateX = diff > 0 ? '130%' : '-130%';
                scale = 0.7;
                opacity = 0;
                blur = 4;
                zIndex = 0;
                pointerEvents = 'none';
              }

              return (
                <div
                  key={item.id}
                  onClick={() => handleCardClick(idx)}
                  style={{
                    transform: `translate(-50%, -50%) translateX(${translateX}) scale(${scale})`,
                    zIndex,
                    opacity,
                    filter: `blur(${blur}px)`,
                    pointerEvents,
                    transition: 'transform 700ms cubic-bezier(0.25, 1, 0.5, 1), opacity 700ms cubic-bezier(0.25, 1, 0.5, 1), filter 700ms cubic-bezier(0.25, 1, 0.5, 1)',
                  }}
                  className={`absolute left-1/2 top-1/2 w-[88%] sm:w-[74%] md:w-[62%] lg:w-[58%] h-[350px] sm:h-[400px] md:h-[440px] lg:h-[460px] rounded-2xl sm:rounded-3xl overflow-hidden cursor-pointer select-none bg-[#071827] border transition-all duration-300 ${
                    isCenter
                      ? 'border-slate-200/90 shadow-[0_25px_60px_-15px_rgba(7,24,39,0.35),0_0_40px_rgba(8,185,232,0.18)] ring-1 ring-[#08B9E8]/40 hover:border-[#08B9E8] hover:shadow-[0_30px_70px_-12px_rgba(8,185,232,0.3)]'
                      : 'border-slate-300/70 hover:border-[#08B9E8]/70 hover:opacity-90 hover:scale-[0.86] hover:blur-0 shadow-lg'
                  }`}
                >
                  <div className="relative w-full h-full group overflow-hidden">
                    {/* Event Photo */}
                    <img
                      src={getMediaUrl(item.image)}
                      alt={item.title}
                      className={`w-full h-full object-cover transition-transform duration-700 ${
                        isCenter ? 'group-hover:scale-105' : ''
                      }`}
                      onError={(e) => {
                        (e.target as HTMLImageElement).src = '/images/placeholder.jpg';
                      }}
                      referrerPolicy="no-referrer"
                    />

                    {/* Gradient Vignette Overlay */}
                    <div className="absolute inset-0 bg-gradient-to-t from-[#071827]/90 via-[#071827]/30 to-transparent pointer-events-none" />

                    {/* Top-Left Category Badge */}
                    <div className="absolute top-4 sm:top-5 left-4 sm:left-5 z-10">
                      <span className="px-3 sm:px-3.5 py-1 sm:py-1.5 rounded-full bg-[#071827]/80 backdrop-blur-md border border-[#08B9E8]/50 text-[#08B9E8] text-xs sm:text-sm font-bold tracking-wide shadow-md">
                        {item.category}
                      </span>
                    </div>

                    {/* Bottom Content: Title and Explore Gallery */}
                    <div className="absolute bottom-0 inset-x-0 p-5 sm:p-7 md:p-8 text-left z-10">
                      <h3 className="text-xl sm:text-2xl md:text-3xl font-extrabold text-white tracking-tight leading-snug group-hover:text-[#08B9E8] transition-colors">
                        {item.title}
                      </h3>
                      {isCenter && (
                        <div className="mt-3 flex items-center gap-1.5 text-xs sm:text-sm font-bold text-white group-hover:text-[#08B9E8] transition-colors">
                          <span>Explore Gallery</span>
                          <ArrowRight className="w-4 h-4 transition-transform duration-300 group-hover:translate-x-1.5" />
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Pagination Indicators */}
        <div className="flex items-center justify-center gap-2 mt-6 sm:mt-8 z-20 relative">
          {filteredList.map((_, idx) => (
            <button
              key={idx}
              onClick={() => setActiveIndex(idx)}
              aria-label={`Go to slide ${idx + 1}`}
              className={`h-2.5 rounded-full transition-all duration-400 focus:outline-none focus:ring-2 focus:ring-[#08B9E8] cursor-pointer ${
                idx === activeIndex
                  ? 'w-8 bg-[#08B9E8] shadow-[0_0_12px_rgba(8,185,232,0.6)]'
                  : 'w-2.5 bg-slate-300 hover:bg-slate-400'
              }`}
            />
          ))}
        </div>
      </div>

      {/* ========================================================
          INTERACTIVE PHOTO GALLERY MODAL
      ======================================================== */}
      {isModalOpen && activeModalItem && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 md:p-6 bg-[#071827]/90 backdrop-blur-md animate-fadeIn overflow-y-auto overscroll-contain"
          onClick={() => setIsModalOpen(false)}
        >
          <div
            className="relative w-[95vw] max-w-5xl lg:max-w-6xl bg-[#081524] rounded-2xl sm:rounded-3xl border border-slate-700/80 shadow-[0_25px_80px_rgba(0,0,0,0.85),0_0_50px_rgba(8,185,232,0.18)] overflow-hidden flex flex-col max-h-[90vh] my-auto overscroll-contain"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Top Header */}
            <div className="px-4 sm:px-6 py-3 sm:py-3.5 border-b border-slate-800 bg-[#071827] shrink-0 z-20">
              <div className="flex items-center justify-between gap-3">
                {/* Left: Badge & Big Prominent Title */}
                <div className="flex items-center gap-2.5 sm:gap-3.5 min-w-0">
                  <span className="px-3 py-1 rounded-full bg-[#08B9E8]/15 border border-[#08B9E8]/40 text-[#08B9E8] text-xs sm:text-sm font-extrabold tracking-wide shrink-0 shadow-[0_0_15px_rgba(8,185,232,0.15)]">
                    {activeModalItem.category}
                  </span>
                  <h2 className="text-base sm:text-xl md:text-2xl font-extrabold text-white tracking-tight truncate leading-tight">
                    {activeModalItem.title}
                  </h2>
                </div>

                {/* Right: Counter & Close Button */}
                <div className="flex items-center gap-2.5 shrink-0">
                  <span className="text-xs text-slate-300 font-semibold bg-slate-800/90 border border-slate-700/80 px-2.5 py-1 rounded-full hidden sm:inline">
                    Photo <span className="text-[#08B9E8] font-bold">{modalPhotoIndex + 1}</span> of {safePhotos.length}
                  </span>
                  <button
                    onClick={() => setIsModalOpen(false)}
                    aria-label="Close modal"
                    className="w-8 h-8 sm:w-9 sm:h-9 rounded-full bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-300 hover:text-white transition-all flex items-center justify-center focus:outline-none focus:ring-2 focus:ring-[#08B9E8] shadow-md hover:scale-105 cursor-pointer"
                  >
                    <X className="w-4 h-4 sm:w-5 sm:h-5" />
                  </button>
                </div>
              </div>

              {/* Integrated Year Category Filter Tabs */}
              {availableYears.length > 1 && (
                <div className="flex items-center gap-2.5 mt-2.5 pt-2.5 border-t border-slate-800/80 overflow-x-auto scrollbar-none">
                  <span className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1.5 mr-1 shrink-0">
                    <Calendar className="w-3.5 h-3.5 text-[#08B9E8]" />
                    Filter by Year:
                  </span>
                  <div className="inline-flex p-0.5 rounded-lg bg-slate-900/90 border border-slate-800 gap-1 shrink-0">
                    <button
                      onClick={() => handleYearChange('All')}
                      className={`px-3 py-1 rounded-md text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer ${
                        modalSelectedYear === 'All'
                          ? 'bg-[#08B9E8] text-[#071827] shadow-sm font-extrabold'
                          : 'text-slate-300 hover:text-white hover:bg-slate-800'
                      }`}
                    >
                      All Photos
                      <span
                        className={`px-1.5 py-0.2 rounded-full text-[10px] ${
                          modalSelectedYear === 'All'
                            ? 'bg-[#071827]/20 text-[#071827] font-extrabold'
                            : 'bg-slate-800 text-slate-400 font-semibold'
                        }`}
                      >
                        {allEventPhotos.length}
                      </span>
                    </button>
                    {availableYears.map((yr) => {
                      const yrCount = allEventPhotos.filter((p) => p.year === yr).length;
                      const isSelected = modalSelectedYear === yr;
                      return (
                        <button
                          key={yr}
                          onClick={() => handleYearChange(yr)}
                          className={`px-3 py-1 rounded-md text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer ${
                            isSelected
                              ? 'bg-[#08B9E8] text-[#071827] shadow-sm font-extrabold'
                              : 'text-slate-300 hover:text-white hover:bg-slate-800'
                          }`}
                        >
                          {yr}
                          {yrCount > 0 && (
                            <span
                              className={`px-1.5 py-0.2 rounded-full text-[10px] ${
                                isSelected
                                  ? 'bg-[#071827]/20 text-[#071827] font-extrabold'
                                  : 'bg-slate-800 text-slate-400 font-semibold'
                              }`}
                            >
                              {yrCount}
                            </span>
                          )}
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>

            {/* Modal Scrollable Content Area */}
            <div className="flex-1 overflow-y-auto overscroll-contain scrollbar-thin min-h-0 flex flex-col">
              {/* Full Cover Image Stage with Auto-Fit (No cutting/cropping) */}
              <div className="relative w-full h-[320px] sm:h-[400px] md:h-[460px] lg:h-[520px] max-h-[65vh] overflow-hidden bg-[#050e18] flex items-center justify-center shrink-0 group">
                {/* Ambient Blurred Backdrop for Cinematic Letterbox */}
                <div
                  className="absolute inset-0 bg-cover bg-center blur-2xl opacity-20 scale-110 pointer-events-none"
                  style={{
                    backgroundImage: `url(${getMediaUrl(currentActivePhoto.image)})`,
                  }}
                />

                <img
                  src={getMediaUrl(currentActivePhoto.image)}
                  alt={getCustomPhotoTitle(currentActivePhoto.title, activeModalItem.title) || activeModalItem.title}
                  className="relative z-1 max-w-full max-h-full w-auto h-auto object-contain transition-all duration-300 select-none shadow-2xl"
                  onError={(e) => {
                    (e.target as HTMLImageElement).src = '/images/placeholder.jpg';
                  }}
                  referrerPolicy="no-referrer"
                />

                {/* Prev / Next Navigation Floating Buttons */}
                {safePhotos.length > 1 && (
                  <>
                    <button
                      onClick={handleModalPrev}
                      aria-label="Previous photo"
                      className="absolute left-3 sm:left-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-black/70 hover:bg-[#08B9E8] text-white hover:text-[#071827] backdrop-blur-md border border-white/20 hover:scale-105 shadow-xl transition-all flex items-center justify-center focus:outline-none z-10 cursor-pointer"
                    >
                      <ChevronLeft className="w-5 h-5 sm:w-6 sm:h-6" />
                    </button>
                    <button
                      onClick={handleModalNext}
                      aria-label="Next photo"
                      className="absolute right-3 sm:right-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-black/70 hover:bg-[#08B9E8] text-white hover:text-[#071827] backdrop-blur-md border border-white/20 hover:scale-105 shadow-xl transition-all flex items-center justify-center focus:outline-none z-10 cursor-pointer"
                    >
                      <ChevronRight className="w-5 h-5 sm:w-6 sm:h-6" />
                    </button>
                  </>
                )}
              </div>

              {/* Modal Bottom Summary Panel & Thumbnails Strip */}
              <div className="p-3.5 sm:p-4 md:p-5 bg-[#06111E] border-t border-slate-800 text-left shrink-0 mt-auto">
                {/* Header row: only displays custom title if entered */}
                {(() => {
                  const customTitle = getCustomPhotoTitle(currentActivePhoto.title, activeModalItem.title);
                  const customCaption = getCustomPhotoCaption(currentActivePhoto.caption);

                  return (
                    <>
                      <div className="flex flex-col sm:flex-row sm:items-baseline justify-between gap-1 mb-1.5">
                        <div className="flex items-center gap-2 flex-wrap">
                          {customTitle ? (
                            <h3 className="text-base sm:text-lg md:text-xl font-extrabold text-white leading-tight">
                              {customTitle}
                            </h3>
                          ) : null}
                          {currentActivePhoto.year && (
                            <span className="px-2 py-0.5 rounded-full bg-[#08B9E8]/15 border border-[#08B9E8]/35 text-[#08B9E8] text-xs font-bold">
                              {currentActivePhoto.year}
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-slate-400 font-medium shrink-0">
                          {modalSelectedYear !== 'All' ? `Filtered by ${modalSelectedYear}` : 'All photos'} ({safePhotos.length} {safePhotos.length === 1 ? 'item' : 'items'})
                        </p>
                      </div>

                      {customCaption ? (
                        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed line-clamp-2 mb-3">
                          {customCaption}
                        </p>
                      ) : null}
                    </>
                  );
                })()}

                {/* Thumbnails Strip with Year Badges */}
                <div className="flex items-center gap-2 sm:gap-2.5 overflow-x-auto no-scrollbar scrollbar-none pb-1 pt-0.5">
                  {safePhotos.map((photo, idx) => (
                    <button
                      key={photo.id || idx}
                      onClick={() => setModalPhotoIndex(idx)}
                      className={`relative w-20 h-14 sm:w-24 sm:h-16 rounded-xl overflow-hidden shrink-0 border transition-all duration-200 focus:outline-none group cursor-pointer ${
                        idx === modalPhotoIndex
                          ? 'border-[#08B9E8] ring-2 ring-[#08B9E8]/80 scale-105 shadow-[0_0_15px_rgba(8,185,232,0.4)]'
                          : 'border-slate-700/80 opacity-60 hover:opacity-100 hover:border-slate-500'
                      }`}
                    >
                      <img
                        src={getMediaUrl(photo.image)}
                        alt={getCustomPhotoTitle(photo.title) || `Photo ${idx + 1}`}
                        className="w-full h-full object-cover group-hover:scale-105 transition-transform"
                        onError={(e) => {
                          (e.target as HTMLImageElement).src = '/images/placeholder.jpg';
                        }}
                        referrerPolicy="no-referrer"
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent pointer-events-none" />
                      <span className="absolute top-1 right-1 text-[9px] font-bold text-[#08B9E8] bg-black/80 px-1.5 py-0.5 rounded-full border border-[#08B9E8]/30">
                        {photo.year}
                      </span>
                      <span className="absolute bottom-1 left-1.5 text-[10px] font-bold text-white bg-black/80 px-1.5 py-0.5 rounded">
                        #{idx + 1}
                      </span>
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
};
